[default]
# API settings
api_prefix = "/api/v1"
debug = false
project_name  = "Zoom Transcript Summarizer"
version = "1.0.0"
allowed_extensions = "vtt"

# Model settings
model_name = "nguyenanhhuy248/gemma-2b-it-samsum"
max_token_limit = 8192