version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: zoom-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/app/config/.secrets.toml
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: zoom-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
